import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Footer } from '../components/FooterBar/FooterBar'
import { HeaderBar } from '../components/HeaderBar/HeaderBar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Owain's corner on the Web</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        
      <HeaderBar></HeaderBar>

      <main>
        <h1>Dit is de main</h1>
      </main>

      <Footer></Footer>
    </div>
  )
}
